# Generated by Django 2.2.2 on 2022-07-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publisher_app.CustomarAccount')),
            ],
            options={
                'db_table': 'gatewaye_payment_list',
            },
        ),
    ]
