# Generated by Django 2.2.2 on 2022-09-24 10:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherprofile',
            name='refund_policy',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='publisherprofile',
            name='shipping_policy',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='publisherprofile',
            name='terms_condition',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisherprofile',
            name='about_content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisherprofile',
            name='pro_details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
