# Generated by Django 2.2.2 on 2022-04-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0003_auto_20220420_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewPdfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='images/preview_images')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('book_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publisher_app.BookList')),
            ],
            options={
                'db_table': 'preview_pdf_file',
            },
        ),
    ]
