# Generated by Django 2.2.2 on 2022-04-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0004_previewpdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewpdffile',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='images/preview_pdf'),
        ),
    ]
