# Generated by Django 2.2.2 on 2022-10-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0004_auto_20221001_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
