# Generated by Django 2.2.2 on 2022-10-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0005_productlist_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='product_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
