# Generated by Django 2.2.2 on 2022-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0005_auto_20220420_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewpdffile',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
