# Generated by Django 2.2.2 on 2022-10-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0007_productlist_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='edition',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='weight',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
