# Generated by Django 2.2.2 on 2022-10-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0008_auto_20221002_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='product_origin',
        ),
    ]
