# Generated by Django 2.2.2 on 2022-10-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_app', '0010_auto_20221003_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publisher_app.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publisher_app.ProductSubCategory'),
        ),
    ]
